name: Build Docker containers
on:
  push:
    branches:
      - master
jobs:
  build-client:
    name: Build and push client/ Docker container
    runs-on: ubuntu-latest
    steps:
      - name: Thing
        run: echo . ${{ secrets.DOCKERHUB_USERNAME }} .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
